### ISSUE TITLE
Building project

### ISSUE THREAD

**Issue by jQrgen** [navi25/SunRise#1]
Hello Navi

I want to learn from your example but i get the issues in the picture below when building it.

Seems to me like some files are missing from the repo

![screen shot 2018-09-18 at 13 06 15](https://user-images.githubusercontent.com/3964957/45686228-c52c0700-bb43-11e8-8366-62fa96af5c8b.png)

JQ

**Comment by navi25** [comment]
Hi JQ,
Sorry for the trouble.
But I haven't yet updated the project and am planning to do it by this
weekend.
Navendra Jha

**Comment by navi25** [comment]
It's been fixed. Closing the issue.
